# Basic Site Settings
title:
  - zh: GloomyGhost 的博客
  - en: GloomyGhost Blog
  - jp: グルーミーゴーストのブログ

title-display: zej

email: gloomyghost@gloomyghost.com
description: >-
  
baseurl: ""
url: ""

# Social Media Settings
twitter_username: jekyllrb
github_username: GloomyGhost-MosquitoSeal

# Build Settings
