# Site settings 配置站点
title: "柚木鉉の空間 | GloomyGhost Blog"
home-title: 柚木鉉の空間
description: C'est pour cela que je suis née Ne me plaignez pas
keyword: "GloomyGhost, C++, CPP, JavaScript, Web, WWW, Blog"
url: ""
baseurl: ""

version: 0.4.1

# Navigation links 导航链接
nav:
  home: "/"
  tags: "/page/tags"
  about: "/page/about"
  links: "/page/links"
  promotion: "/page/promotion"
  tenebrous: "https://www.gloomyghost.com/Tenebrous/"

# Footer 创立日前
footer:
  since: 2014

# Funny Title
funny_title: true

# beian 备案号
beian: <a href="https://beian.miit.gov.cn/">滇ICP备19005195号-1</a>

# hitokoto url 一言地址
hitokoto: https://v1.hitokoto.cn/?encode=js&select=%23hitokoto

# Author 配置博主信息
author: 柚木鉉
nickname: GloomyGhost | 蚊香豹
bio: Singing Synthesis, Operating System, Web Develop, IOT, Psychology, 中文/English/日本語OK, Chinese <br> (｀・∀・´)
avatar: "/assets/img/profile.jpg"

# Search
search: true

# 赞赏
zanshang: true

# advertisement 广告
ad: true

# Night mode
nightMode: false

# MathJax
mathjax: true

# Math Plot
plot: true

# Chem Plot 
cmplot: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# theme color 主题皮肤
theme-color: "default" # default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: "circuitBoard"

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: "mailto:gloomyghost@gloomyghost.com"
  zhihu: "https://www.zhihu.com/people/gloomyghost"
  github: "https://github.com/YuzukiTsuru"
  qq: "http://wpa.qq.com/msgrd?v=3&uin=2427346650&site=qq&menu=yes"
  twitter: "https://twitter.com/GLGH_"
  bilibili: "https://space.bilibili.com/24622028"

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 10
paginate_path: "page:num"
exclude: [.gitignore', "README.md"]

# Compress
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
permalink: /live/:title.aspx

# Plugins
plugins: [jekyll-paginate]